name: Check for new versions

on:
  schedule:
    - cron: "0 0 * * MON" # Run weekly on Monday
  workflow_dispatch: # Allow manual triggers

jobs:
  check-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Check Alpine version
        id: alpine
        run: |
          LATEST=$(wget -qO- https://registry.hub.docker.com/v2/repositories/library/alpine/tags | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+$' | sort -V | tail -n1)
          CURRENT=$(grep 'ALPINE_VERSION=' Dockerfile | cut -d'=' -f2)
          echo "current=$CURRENT" >> $GITHUB_OUTPUT
          echo "latest=$LATEST" >> $GITHUB_OUTPUT

      - name: Check Ofelia version
        id: ofelia
        run: |
          LATEST=$(curl -s https://api.github.com/repos/mcuadros/ofelia/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          CURRENT=$(grep 'OFELIA_VERSION=' Dockerfile | cut -d'=' -f2)
          echo "current=$CURRENT" >> $GITHUB_OUTPUT
          echo "latest=$LATEST" >> $GITHUB_OUTPUT

      - name: Check Go Task version
        id: gotask
        run: |
          LATEST=$(curl -s https://api.github.com/repos/go-task/task/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          CURRENT=$(grep 'GO_TASK_VERSION=' Dockerfile | cut -d'=' -f2)
          echo "current=$CURRENT" >> $GITHUB_OUTPUT
          echo "latest=$LATEST" >> $GITHUB_OUTPUT

      - name: Create Pull Request if updates available
        if: steps.alpine.outputs.current != steps.alpine.outputs.latest || steps.ofelia.outputs.current != steps.ofelia.outputs.latest || steps.gotask.outputs.current != steps.gotask.outputs.latest
        run: |
          # Update versions in Dockerfile
          sed -i "s/ALPINE_VERSION=${{ steps.alpine.outputs.current }}/ALPINE_VERSION=${{ steps.alpine.outputs.latest }}/" Dockerfile
          sed -i "s/OFELIA_VERSION=${{ steps.ofelia.outputs.current }}/OFELIA_VERSION=${{ steps.ofelia.outputs.latest }}/" Dockerfile
          sed -i "s/GO_TASK_VERSION=${{ steps.gotask.outputs.current }}/GO_TASK_VERSION=${{ steps.gotask.outputs.latest }}/" Dockerfile

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        if: steps.alpine.outputs.current != steps.alpine.outputs.latest || steps.ofelia.outputs.current != steps.ofelia.outputs.latest || steps.gotask.outputs.current != steps.gotask.outputs.latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          commit-message: Update dependencies
          title: "📦 Update dependency versions"
          body: |
            Updates detected for the following dependencies:

            ${{ steps.alpine.outputs.current != steps.alpine.outputs.latest && '- Alpine: `' + steps.alpine.outputs.current + '` -> `' + steps.alpine.outputs.latest + '`' || '' }}
            ${{ steps.ofelia.outputs.current != steps.ofelia.outputs.latest && '- Ofelia: `' + steps.ofelia.outputs.current + '` -> `' + steps.ofelia.outputs.latest + '`' || '' }}
            ${{ steps.gotask.outputs.current != steps.gotask.outputs.latest && '- Go Task: `' + steps.gotask.outputs.current + '` -> `' + steps.gotask.outputs.latest + '`' || '' }}

            This PR was automatically generated by GitHub Actions.
          branch: update-versions
          labels: |
            dependencies
            automated pr
